### ISSUE TITLE
undefined body throws error on setInterval

### ISSUE THREAD

**Issue by amragaey360** [EvanBoyle/AzureSearchNodeJSIndexerDemo#2]
on running `npm run indexDocuments` I got the below error. As the code isn't handling undefined body response in setInterval for indexer status.

`success, items processed: 6696
undefined
undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Request._callback (C:\Users\AmrRagaey-PC\Desktop\azuredemo\js\DataIndexer\DataIndexer.js:228:31)
    at self.callback (C:\Users\AmrRagaey-PC\Desktop\azuredemo\node_modules\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\AmrRagaey-PC\Desktop\azuredemo\node_modules\request\request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
`

**Comment by konstmsu** [comment]
@amragaey360 you need to modify `config.js` to supply **apiKey**, **queyrKey** and **serviceUrl** as described in https://docs.microsoft.com/en-us/azure/search/search-get-started-nodejs#find-the-service-name-and-api-key-of-your-azure-search-service

**Comment by konstmsu** [comment]
Although it seems that your upload has completed successfully so I'm probably wrong.
